### ISSUE TITLE
Deploy ONAP-Amsterdam to OpenStack on Packet.net using VNF demo vagrant scripts

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#4]
- [x] deploy OpenStack, see #1 

- [x] make fixes to deploy scripts to get vagrant and OpenStack to work as expected

- [x] attempt to deploy ONAP using heat templates from onap demo

- [ ] debug ONAP SO error from https://github.com/cncf/onap-demo/issues/5

**Comment by taylor** [comment]
Issue: ONAP mso-api-handler-infra failed to start service - class path issue?

```
17:00:36,019 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment MSOInfrastructureBPMN-1.2
.1.war (runtime-name: MSOInfrastructureBPMN-1.2.1.war) in 80492ms
17:00:55,673 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry scala-reflect.jar in /content/mso-api-handler-infra-1.2.1.war/WEB-INF/lib/scala-compiler-2.12.4.jar  does not point to a valid jar for a Class-Path reference.   17:00:55,679 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry scala-library.jar in /content/mso-api-handler-infra-1.2.1.war/WEB-INF/lib/scala-compiler-2.12.4.jar  does not point to a valid jar for a Class-Path reference.   17:00:56,353 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.deployment.unit."mso-api-handler-infra-1.2.1.war".STRUCTURE: org.jboss.msc.service.StartException in service jboss.deployment.unit."mso-api-handler-infra-
1.2.1.war".STRUCTURE: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Container is down
        at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:716)
        at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
        at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
        at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)                                                        at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2401)
        at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317)                                                      at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:208)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)                                at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        ... 3 more
```

**Comment by lixuna** [comment]
closing as invalid
